export const actionTypes = {
  SIGN_IN: "SIGN_IN",
  SIGN_UP: "SIGN_UP",
  LOG_OUT: "LOG_OUT",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  ALL_BOOKS: "ALL_BOOKS",
  SHOW_ALL_BOOKS: "SHOW_ALL_BOOKS",
  SHOW_SINGLE_BOOK: "SHOW_SINGLE_BOOK",
};
